pipeline:
  build:
    image: plugins/docker
    registry: registry.dryusdan.fr
    repo: registry.dryusdan.fr/dryusdan/diaspora
    secrets: [ docker_username, docker_password ]

  push:
    image: appleboy/drone-git-push
    branch: master
    remote: git@github.com:Dryusdan/docker-diaspora.git
    secrets: [ git_push_ssh_key ]

